//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class LidarScanMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/LidarScan";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public float angle_min;
        public float angle_max;
        public float angle_increment;
        public float time_increment;
        public float scan_time;
        public float range_min;
        public float range_max;
        public float[] ranges;
        public float[] intensities;

        public LidarScanMsg()
        {
            this.header = new HeaderMsg();
            this.angle_min = 0.0f;
            this.angle_max = 0.0f;
            this.angle_increment = 0.0f;
            this.time_increment = 0.0f;
            this.scan_time = 0.0f;
            this.range_min = 0.0f;
            this.range_max = 0.0f;
            this.ranges = new float[0];
            this.intensities = new float[0];
        }

        public LidarScanMsg(HeaderMsg header, float angle_min, float angle_max, float angle_increment, float time_increment, float scan_time, float range_min, float range_max, float[] ranges, float[] intensities)
        {
            this.header = header;
            this.angle_min = angle_min;
            this.angle_max = angle_max;
            this.angle_increment = angle_increment;
            this.time_increment = time_increment;
            this.scan_time = scan_time;
            this.range_min = range_min;
            this.range_max = range_max;
            this.ranges = ranges;
            this.intensities = intensities;
        }

        public static LidarScanMsg Deserialize(MessageDeserializer deserializer) => new LidarScanMsg(deserializer);

        private LidarScanMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.angle_min);
            deserializer.Read(out this.angle_max);
            deserializer.Read(out this.angle_increment);
            deserializer.Read(out this.time_increment);
            deserializer.Read(out this.scan_time);
            deserializer.Read(out this.range_min);
            deserializer.Read(out this.range_max);
            deserializer.Read(out this.ranges, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.intensities, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.angle_min);
            serializer.Write(this.angle_max);
            serializer.Write(this.angle_increment);
            serializer.Write(this.time_increment);
            serializer.Write(this.scan_time);
            serializer.Write(this.range_min);
            serializer.Write(this.range_max);
            serializer.WriteLength(this.ranges);
            serializer.Write(this.ranges);
            serializer.WriteLength(this.intensities);
            serializer.Write(this.intensities);
        }

        public override string ToString()
        {
            return "LidarScanMsg: " +
            "\nheader: " + header.ToString() +
            "\nangle_min: " + angle_min.ToString() +
            "\nangle_max: " + angle_max.ToString() +
            "\nangle_increment: " + angle_increment.ToString() +
            "\ntime_increment: " + time_increment.ToString() +
            "\nscan_time: " + scan_time.ToString() +
            "\nrange_min: " + range_min.ToString() +
            "\nrange_max: " + range_max.ToString() +
            "\nranges: " + System.String.Join(", ", ranges.ToList()) +
            "\nintensities: " + System.String.Join(", ", intensities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
