//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PoseMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Pose";
        public override string RosMessageName => k_RosMessageName;

        public float[] Xdata;
        public float[] Zdata;

        public PoseMsg()
        {
            this.Xdata = new float[0];
            this.Zdata = new float[0];
        }

        public PoseMsg(float[] Xdata, float[] Zdata)
        {
            this.Xdata = Xdata;
            this.Zdata = Zdata;
        }

        public static PoseMsg Deserialize(MessageDeserializer deserializer) => new PoseMsg(deserializer);

        private PoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.Xdata, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.Zdata, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.Xdata);
            serializer.Write(this.Xdata);
            serializer.WriteLength(this.Zdata);
            serializer.Write(this.Zdata);
        }

        public override string ToString()
        {
            return "PoseMsg: " +
            "\nXdata: " + System.String.Join(", ", Xdata.ToList()) +
            "\nZdata: " + System.String.Join(", ", Zdata.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
