//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class RbtPoseMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/RbtPose";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public float pos_X;
        public float pos_Y;
        public float pos_Z;
        public float rot_X;
        public float rot_Y;
        public float rot_Z;
        public float rot_W;

        public RbtPoseMsg()
        {
            this.header = new HeaderMsg();
            this.pos_X = 0.0f;
            this.pos_Y = 0.0f;
            this.pos_Z = 0.0f;
            this.rot_X = 0.0f;
            this.rot_Y = 0.0f;
            this.rot_Z = 0.0f;
            this.rot_W = 0.0f;
        }

        public RbtPoseMsg(HeaderMsg header, float pos_X, float pos_Y, float pos_Z, float rot_X, float rot_Y, float rot_Z, float rot_W)
        {
            this.header = header;
            this.pos_X = pos_X;
            this.pos_Y = pos_Y;
            this.pos_Z = pos_Z;
            this.rot_X = rot_X;
            this.rot_Y = rot_Y;
            this.rot_Z = rot_Z;
            this.rot_W = rot_W;
        }

        public static RbtPoseMsg Deserialize(MessageDeserializer deserializer) => new RbtPoseMsg(deserializer);

        private RbtPoseMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.pos_X);
            deserializer.Read(out this.pos_Y);
            deserializer.Read(out this.pos_Z);
            deserializer.Read(out this.rot_X);
            deserializer.Read(out this.rot_Y);
            deserializer.Read(out this.rot_Z);
            deserializer.Read(out this.rot_W);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pos_X);
            serializer.Write(this.pos_Y);
            serializer.Write(this.pos_Z);
            serializer.Write(this.rot_X);
            serializer.Write(this.rot_Y);
            serializer.Write(this.rot_Z);
            serializer.Write(this.rot_W);
        }

        public override string ToString()
        {
            return "RbtPoseMsg: " +
            "\nheader: " + header.ToString() +
            "\npos_X: " + pos_X.ToString() +
            "\npos_Y: " + pos_Y.ToString() +
            "\npos_Z: " + pos_Z.ToString() +
            "\nrot_X: " + rot_X.ToString() +
            "\nrot_Y: " + rot_Y.ToString() +
            "\nrot_Z: " + rot_Z.ToString() +
            "\nrot_W: " + rot_W.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
